// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_loco_cpp
Rcpp::List run_loco_cpp(std::string inFile, char del, bool col, bool row, bool zscore, int thread, unsigned int correlatedSetMode, std::string cellStateGeneFile, std::string correlationStateGeneFile, unsigned int numberNeighbourhoods, unsigned int neighborhoodSize, int neighborhoodKNN, double correlationCutoff, int permutations, int minSetSize, double corrSetAbundance, std::string correlationType, bool calcFeatureSets);
RcppExport SEXP _loco_run_loco_cpp(SEXP inFileSEXP, SEXP delSEXP, SEXP colSEXP, SEXP rowSEXP, SEXP zscoreSEXP, SEXP threadSEXP, SEXP correlatedSetModeSEXP, SEXP cellStateGeneFileSEXP, SEXP correlationStateGeneFileSEXP, SEXP numberNeighbourhoodsSEXP, SEXP neighborhoodSizeSEXP, SEXP neighborhoodKNNSEXP, SEXP correlationCutoffSEXP, SEXP permutationsSEXP, SEXP minSetSizeSEXP, SEXP corrSetAbundanceSEXP, SEXP correlationTypeSEXP, SEXP calcFeatureSetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type inFile(inFileSEXP);
    Rcpp::traits::input_parameter< char >::type del(delSEXP);
    Rcpp::traits::input_parameter< bool >::type col(colSEXP);
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< bool >::type zscore(zscoreSEXP);
    Rcpp::traits::input_parameter< int >::type thread(threadSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type correlatedSetMode(correlatedSetModeSEXP);
    Rcpp::traits::input_parameter< std::string >::type cellStateGeneFile(cellStateGeneFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type correlationStateGeneFile(correlationStateGeneFileSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type numberNeighbourhoods(numberNeighbourhoodsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type neighborhoodSize(neighborhoodSizeSEXP);
    Rcpp::traits::input_parameter< int >::type neighborhoodKNN(neighborhoodKNNSEXP);
    Rcpp::traits::input_parameter< double >::type correlationCutoff(correlationCutoffSEXP);
    Rcpp::traits::input_parameter< int >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< int >::type minSetSize(minSetSizeSEXP);
    Rcpp::traits::input_parameter< double >::type corrSetAbundance(corrSetAbundanceSEXP);
    Rcpp::traits::input_parameter< std::string >::type correlationType(correlationTypeSEXP);
    Rcpp::traits::input_parameter< bool >::type calcFeatureSets(calcFeatureSetsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_loco_cpp(inFile, del, col, row, zscore, thread, correlatedSetMode, cellStateGeneFile, correlationStateGeneFile, numberNeighbourhoods, neighborhoodSize, neighborhoodKNN, correlationCutoff, permutations, minSetSize, corrSetAbundance, correlationType, calcFeatureSets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_loco_run_loco_cpp", (DL_FUNC) &_loco_run_loco_cpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_loco(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
