# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_loco_cpp <- function(inFile, del, col, row, zscore, thread, correlatedSetMode, numberCorrelations, cellStateGeneFile, correlationStateGeneFile, numberNeighbourhoods, neighborhoodSize, neighborhoodKNN, correlationCutoff, permutations, minSetSize, corrSetAbundance) {
    .Call('_loco_run_loco_cpp', PACKAGE = 'loco', inFile, del, col, row, zscore, thread, correlatedSetMode, numberCorrelations, cellStateGeneFile, correlationStateGeneFile, numberNeighbourhoods, neighborhoodSize, neighborhoodKNN, correlationCutoff, permutations, minSetSize, corrSetAbundance)
}

